driver:
  name: ec2
  aws_ssh_key_id: KEY-NAME
  security_group_ids: ["sg-xxx"]
  region: eu-west-1
  availability_zone: eu-west-1a
  require_chef_omnibus: true
  subnet_id: subnet-xxx
  instance_type: m3.medium

transport:
  ssh_key: PATH
  username: ubuntu

provisioner:
  name: chef_solo

platforms:
  - name: amazon
    driver:
      image_id: ami-1b791862
      tags:
        Name: Hello-World-ChefKitchen
        created-by: test-kitchen
      iam_profile_name: hello-world

suites:
  - name: default
    run_list:
      - recipe[hello-world::default]
    attributes:


